// <auto-generated />
namespace EpiBookingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Corrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corrections));
        
        string IMigrationMetadata.Id
        {
            get { return "201903261051161_Corrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
